import './globals.css'
import Footer from './components/footerMenu/page'
import Header from './components/header/page'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Layout =({ children }) => {
  return (
    <div className='content'>
      <Header />
      {children}
      <Footer />
    </div>
  )
}

export default Layout

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
